<?php
/**
 * Attributes File.
 *
 * @since x.x.x
 *
 * @package uagb
 */

return array(
	'classMigrate' => false,
	'blockName'    => 'slider',
	'topPaddingDesktop'                 => 20,
	'bottomPaddingDesktop'              => 20,
	'leftPaddingDesktop'                => 20,
	'rightPaddingDesktop'               => 20,
	'topPaddingTablet'                  => '',
	'bottomPaddingTablet'               => '',
	'leftPaddingTablet'                 => '',
	'rightPaddingTablet'                => '',
	'topPaddingMobile'                  => '',
	'bottomPaddingMobile'               => '',
	'leftPaddingMobile'                 => '',
	'rightPaddingMobile'                => '',
	'paddingType'                       => 'px',
	'paddingTypeTablet'                 => 'px',
	'paddingTypeMobile'                 => 'px',
	'paddingLink'                       => true,
	'topMarginDesktop'                  => '',
	'bottomMarginDesktop'               => '',
	'leftMarginDesktop'                 => '',
	'rightMarginDesktop'                => '',
	'topMarginTablet'                   => '',
	'bottomMarginTablet'                => '',
	'leftMarginTablet'                  => '',
	'rightMarginTablet'                 => '',
	'topMarginMobile'                   => '',
	'bottomMarginMobile'                => '',
	'leftMarginMobile'                  => '',
	'rightMarginMobile'                 => '',
	'marginType'                        => 'px',
	'marginTypeTablet'                  => 'px',
	'marginTypeMobile'                  => 'px',
	'marginLink'                        => true,
	'backgroundType'                    => 'none',
	'backgroundImageDesktop'            => '',
	'backgroundImageTablet'             => '',
	'backgroundImageMobile'             => '',
	'backgroundPositionDesktop'         => array(
		'x' => 0.5,
		'y' => 0.5,
	),
	'backgroundPositionTablet'          => '',
	'backgroundPositionMobile'          => '',
	'backgroundSizeDesktop'             => 'cover',
	'backgroundSizeTablet'              => '',
	'backgroundSizeMobile'              => '',
	'backgroundRepeatDesktop'           => 'no-repeat',
	'backgroundRepeatTablet'            => '',
	'backgroundRepeatMobile'            => '',
	'backgroundAttachmentDesktop'       => 'scroll',
	'backgroundAttachmentTablet'        => '',
	'backgroundAttachmentMobile'        => '',
	'backgroundColor'                   => '',
	'backgroundOpacity'                 => '',
	'backgroundImageColor'              => '#FFFFFF75',
	'gradientValue'                     => 'linear-gradient(90deg, rgba(6, 147, 227, 0.5) 0%, rgba(155, 81, 224, 0.5) 100%)',
);
