<?php
/**
 * Attributes File.
 *
 * @since 2.0.0
 *
 * @package uagb
 */

$border_attribute = UAGB_Block_Helper::uag_generate_border_attribute(
	'block'
);

return array_merge(
	array(
		'block_id'                    => '',
		'backgroundType'              => 'none',
		'backgroundImageDesktop'      => '',
		'backgroundImageTablet'       => '',
		'backgroundImageMobile'       => '',
		'backgroundPositionDesktop'   => array(
			'x' => 0.5,
			'y' => 0.5,
		),
		'backgroundPositionTablet'    => '',
		'backgroundPositionMobile'    => '',
		'backgroundSizeDesktop'       => 'cover',
		'backgroundSizeTablet'        => '',
		'backgroundSizeMobile'        => '',
		'backgroundRepeatDesktop'     => 'no-repeat',
		'backgroundRepeatTablet'      => '',
		'backgroundRepeatMobile'      => '',
		'backgroundAttachmentDesktop' => 'scroll',
		'backgroundAttachmentTablet'  => '',
		'backgroundAttachmentMobile'  => '',
		'backgroundColor'             => '',
		'backgroundOpacity'           => '',
		'backgroundImageColor'        => '#FFFFFF75',
		'gradientValue'               => 'linear-gradient(90deg, rgba(6, 147, 227, 0.5) 0%, rgba(155, 81, 224, 0.5) 100%)',
		'boxShadowColor'              => '#00000070',
		'boxShadowHOffset'            => 0,
		'boxShadowVOffset'            => 0,
		'boxShadowBlur'               => '',
		'boxShadowSpread'             => '',
		'boxShadowPosition'           => 'outset',
		'boxShadowColorHover'         => '',
		'boxShadowHOffsetHover'       => 0,
		'boxShadowVOffsetHover'       => 0,
		'boxShadowBlurHover'          => '',
		'boxShadowSpreadHover'        => '',
		'boxShadowPositionHover'      => 'outset',

		'topPaddingDesktop'           => '',
		'bottomPaddingDesktop'        => '',
		'leftPaddingDesktop'          => '',
		'rightPaddingDesktop'         => '',
		'topPaddingTablet'            => '',
		'bottomPaddingTablet'         => '',
		'leftPaddingTablet'           => '',
		'rightPaddingTablet'          => '',
		'topPaddingMobile'            => '',
		'bottomPaddingMobile'         => '',
		'leftPaddingMobile'           => '',
		'rightPaddingMobile'          => '',
		'paddingType'                 => 'px',
		'paddingTypeTablet'           => 'px',
		'paddingTypeMobile'           => 'px',
		'paddingLink'                 => true,
		'topMarginDesktop'            => '',
		'bottomMarginDesktop'         => '',
		'leftMarginDesktop'           => '',
		'rightMarginDesktop'          => '',
		'topMarginTablet'             => '',
		'bottomMarginTablet'          => '',
		'leftMarginTablet'            => '',
		'rightMarginTablet'           => '',
		'topMarginMobile'             => '',
		'bottomMarginMobile'          => '',
		'leftMarginMobile'            => '',
		'rightMarginMobile'           => '',
		'marginType'                  => 'px',
		'marginTypeTablet'            => 'px',
		'marginTypeMobile'            => 'px',
		'marginLink'                  => true,
		'rowGapDesktop'               => '',
		'rowGapTablet'                => '',
		'rowGapMobile'                => '',
		'rowGapType'                  => 'px',
		'rowGapTypeTablet'            => 'px',
		'rowGapTypeMobile'            => 'px',
		'backgroundCustomSizeDesktop' => 100,
		'backgroundCustomSizeTablet'  => '',
		'backgroundCustomSizeMobile'  => '',
		'backgroundCustomSizeType'    => '%',
		'overlayType'                 => 'none',
		'customPosition'              => 'default',
		'xPositionDesktop'            => '',
		'xPositionTablet'             => '',
		'xPositionMobile'             => '',
		'xPositionType'               => 'px',
		'xPositionTypeTablet'         => 'px',
		'xPositionTypeMobile'         => 'px',
		'yPositionDesktop'            => '',
		'yPositionTablet'             => '',
		'yPositionMobile'             => '',
		'yPositionType'               => 'px',
		'yPositionTypeTablet'         => 'px',
		'yPositionTypeMobile'         => 'px',
		'backgroundVideoColor'        => '#FFFFFF75',
		'backgroundVideo'             => '',
		'backgroundVideoOpacity'      => 0.5,
	),
	$border_attribute
);
