<?php
/**
 * Block Information & Attributes File.
 *
 * @since 2.0.0
 *
 * @package uagb
 */

return array(
	'classMigrate'                         => false,
	'block_id'                             => '',
	'beforeImage'                          => '',
	'afterImage'                           => '',
	'showLabels'                           => true,
	'showLabelsTablet'                     => false,
	'showLabelsMobile'                     => false,
	'beforeLabel'                          => __( 'Before', 'ultimate-addons-for-gutenberg' ),
	'afterLabel'                           => __( 'After', 'ultimate-addons-for-gutenberg' ),
	'sliderOrientation'                    => 'horizontal',
	'sliderPosition'                       => 50,
	'animateSlider'                        => false,
	'hoverSlider'                          => false,
	'beforeLabelColor'                     => '#ffffff',
	'afterLabelColor'                      => '#ffffff',
	'beforeLabelBgColor'                   => '#000000',
	'afterLabelBgColor'                    => '#000000',
	'beforeLabelOpacity'                   => 1,
	'afterLabelOpacity'                    => 1,
	'beforeLabelHorizontalAlignment'       => 3,
	'afterLabelHorizontalAlignment'        => 97,
	'beforeLabelVerticalAlignment'         => 85,
	'afterLabelVerticalAlignment'          => 85,
	'beforeLabelHorizontalAlignmentTablet' => 3,
	'afterLabelHorizontalAlignmentTablet'  => 97,
	'beforeLabelVerticalAlignmentTablet'   => 85,
	'afterLabelVerticalAlignmentTablet'    => 85,
	'beforeLabelHorizontalAlignmentMobile' => 3,
	'afterLabelHorizontalAlignmentMobile'  => 97,
	'beforeLabelVerticalAlignmentMobile'   => 85,
	'afterLabelVerticalAlignmentMobile'    => 85,
	'labelBorderStyle'                     => 'none',
	'labelBorderWidth'                     => 2,
	'labelBorderRadius'                    => 5,
	'labelBorderColor'                     => '#000000',
	'labelBorderHoverColor'                => '#ffffff',
	'enableSliderElevation'                => true,
	'sliderBoxShadowColor'                 => '#aaaaaa',
	'sliderBoxShadowHOffset'               => 0,
	'sliderBoxShadowVOffset'               => 0,
	'sliderBoxShadowBlur'                  => 15,
	'sliderBoxShadowSpread'                => 5,
	'sliderBoxShadowPosition'              => '',
	'dividerColor'                         => '#ffffff',
	'dividerWidth'                         => 2,
	'handleHoverAnimation'                 => false,
	'sliderWidthUnitDesktop'               => '%',
	'sliderWidthUnitTablet'                => '%',
	'sliderWidthUnitMobile'                => '%',
	'sliderHeightUnitDesktop'              => 'px',
	'sliderHeightUnitTablet'               => 'px',
	'sliderHeightUnitMobile'               => 'px',
	'sliderWidthDesktop'                   => '100',
	'sliderWidthTablet'                    => '100',
	'sliderWidthMobile'                    => '100',
	'sliderHeightDesktop'                  => '720',
	'sliderHeightTablet'                   => '360',
	'sliderHeightMobile'                   => '240',
	'imageDimDesktop'                      => 'full',
	'imageDimTablet'                       => 'full',
	'imageDimMobile'                       => 'full',
);
