<?php
/**
 * Block Information & Attributes File.
 *
 * @since 2.0.0
 *
 * @package uagb
 */

return array(
	'block_id'              => '',
	'widthDesktop'          => 100,
	'widthTablet'           => 100,
	'widthMobile'           => 100,
	'widthType'             => '%',
	'minHeightDesktop'      => '',
	'minHeightTablet'       => '',
	'minHeightMobile'       => '',
	'minHeightType'         => 'px',
	'directionDesktop'      => '',
	'directionTablet'       => '',
	'directionMobile'       => '',
	'alignItemsDesktop'     => '',
	'alignItemsTablet'      => '',
	'alignItemsMobile'      => '',
	'justifyContentDesktop' => '',
	'justifyContentTablet'  => '',
	'justifyContentMobile'  => '',
	'wrapDesktop'           => '',
	'wrapTablet'            => '',
	'wrapMobile'            => '',
	'alignContentDesktop'   => '',
	'alignContentTablet'    => '',
	'alignContentMobile'    => '',
	'backgroundType'        => '',
	'backgroundImage'       => '',
	'backgroundPosition'    => '',
	'backgroundSize'        => '',
	'backgroundRepeat'      => '',
	'backgroundAttachment'  => '',
	'backgroundColor'       => '',
	'backgroundOpacity'     => '',
	'backgroundImageColor'  => '',
	'gradientValue'         => '',
	'borderStyle'           => '',
	'borderWidth'           => '',
	'borderRadius'          => '',
	'borderColor'           => '',
	'borderHoverColor'      => '',
	'boxShadowColor'        => '',
	'boxShadowHOffset'      => '',
	'boxShadowVOffset'      => '',
	'boxShadowBlur'         => '',
	'boxShadowSpread'       => '',
	'boxShadowPosition'     => '',
	'topPaddingDesktop'     => 20,
	'bottomPaddingDesktop'  => 20,
	'leftPaddingDesktop'    => 20,
	'rightPaddingDesktop'   => 20,
	'topPaddingTablet'      => '',
	'bottomPaddingTablet'   => '',
	'leftPaddingTablet'     => '',
	'rightPaddingTablet'    => '',
	'topPaddingMobile'      => '',
	'bottomPaddingMobile'   => '',
	'leftPaddingMobile'     => '',
	'rightPaddingMobile'    => '',
	'paddingType'           => 'px',
	'paddingLink'           => '',
	'topMarginDesktop'      => '',
	'bottomMarginDesktop'   => '',
	'leftMarginDesktop'     => '',
	'rightMarginDesktop'    => '',
	'topMarginTablet'       => '',
	'bottomMarginTablet'    => '',
	'leftMarginTablet'      => '',
	'rightMarginTablet'     => '',
	'topMarginMobile'       => '',
	'bottomMarginMobile'    => '',
	'leftMarginMobile'      => '',
	'rightMarginMobile'     => '',
	'marginType'            => 'px',
	'marginLink'            => '',
	'rowGapDesktop'         => '',
	'rowGapTablet'          => '',
	'rowGapMobile'          => '',
	'rowGapType'            => 'px',
	'columnGapDesktop'      => '',
	'columnGapTablet'       => '',
	'columnGapMobile'       => '',
	'columnGapType'         => 'px',
);
