<?php
/**
 * Attributes File.
 *
 * @since 2.1.0
 *
 * @package uagb
 */

return array_merge(
	array(
		'showLabels'               => true,
		'labelDays'                => __( 'DAYS', 'ultimate-addons-for-gutenberg' ),
		'labelHours'               => __( 'HOURS', 'ultimate-addons-for-gutenberg' ),
		'labelMinutes'             => __( 'MINUTES', 'ultimate-addons-for-gutenberg' ),
		'labelSeconds'             => __( 'SECONDS', 'ultimate-addons-for-gutenberg' ),
		// Digit.
		'digitLoadGoogleFonts'     => false,
		'digitColor'               => '',
		'digitFontFamily'          => 'Default',
		'digitFontWeight'          => '',
		'digitFontStyle'           => 'normal',
		'digitTransform'           => '',
		'digitDecoration'          => '',
		'digitFontSizeType'        => 'px',
		'digitLineHeightType'      => 'em',
		'digitFontSize'            => '',
		'digitFontSizeTablet'      => '',
		'digitFontSizeMobile'      => '',
		'digitLineHeight'          => '',
		'digitLineHeightTablet'    => '',
		'digitLineHeightMobile'    => '',
		'digitTopMargin'           => '',
		'digitRightMargin'         => '',
		'digitBottomMargin'        => '',
		'digitLeftMargin'          => '',
		'digitTopMarginTablet'     => '',
		'digitRightMarginTablet'   => '',
		'digitBottomMarginTablet'  => '',
		'digitLeftMarginTablet'    => '',
		'digitTopMarginMobile'     => '',
		'digitRightMarginMobile'   => '',
		'digitBottomMarginMobile'  => '',
		'digitLeftMarginMobile'    => '',
		'digitMarginUnit'          => 'px',
		'digitMarginUnitTablet'    => 'px',
		'digitMarginUnitMobile'    => 'px',
		// Label.
		'labelLoadGoogleFonts'     => false,
		'labelColor'               => '',
		'labelFontFamily'          => 'Default',
		'labelFontWeight'          => '',
		'labelFontStyle'           => 'normal',
		'labelTransform'           => '',
		'labelDecoration'          => '',
		'labelFontSizeType'        => 'px',
		'labelLineHeightType'      => 'em',
		'labelFontSize'            => '',
		'labelFontSizeTablet'      => '',
		'labelFontSizeMobile'      => '',
		'labelLineHeight'          => '',
		'labelLineHeightTablet'    => '',
		'labelLineHeightMobile'    => '',
		'labelTopMargin'           => '',
		'labelRightMargin'         => '',
		'labelBottomMargin'        => '',
		'labelLeftMargin'          => '',
		'labelTopMarginTablet'     => '',
		'labelRightMarginTablet'   => '',
		'labelBottomMarginTablet'  => '',
		'labelLeftMarginTablet'    => '',
		'labelTopMarginMobile'     => '',
		'labelRightMarginMobile'   => '',
		'labelBottomMarginMobile'  => '',
		'labelLeftMarginMobile'    => '',
		'labelMarginUnit'          => 'px',
		'labelMarginUnitTablet'    => 'px',
		'labelMarginUnitMobile'    => 'px',
		// Block Margin.
		'blockTopMargin'           => '',
		'blockRightMargin'         => '',
		'blockLeftMargin'          => '',
		'blockBottomMargin'        => '',
		'blockTopMarginTablet'     => '',
		'blockRightMarginTablet'   => '',
		'blockLeftMarginTablet'    => '',
		'blockBottomMarginTablet'  => '',
		'blockTopMarginMobile'     => '',
		'blockRightMarginMobile'   => '',
		'blockLeftMarginMobile'    => '',
		'blockBottomMarginMobile'  => '',
		'blockMarginUnit'          => 'px',
		'blockMarginUnitTablet'    => 'px',
		'blockMarginUnitMobile'    => 'px',
		// Block Padding.
		'blockTopPadding'          => '',
		'blockRightPadding'        => '',
		'blockLeftPadding'         => '',
		'blockBottomPadding'       => '',
		'blockTopPaddingTablet'    => '',
		'blockRightPaddingTablet'  => '',
		'blockLeftPaddingTablet'   => '',
		'blockBottomPaddingTablet' => '',
		'blockTopPaddingMobile'    => '',
		'blockRightPaddingMobile'  => '',
		'blockLeftPaddingMobile'   => '',
		'blockBottomPaddingMobile' => '',
		'blockPaddingUnit'         => 'px',
		'blockPaddingUnitTablet'   => 'px',
		'blockPaddingUnitMobile'   => 'px',
		// Box Padding.
		'boxTopPadding'            => '',
		'boxRightPadding'          => '',
		'boxLeftPadding'           => '',
		'boxBottomPadding'         => '',
		'boxTopPaddingTablet'      => '',
		'boxRightPaddingTablet'    => '',
		'boxLeftPaddingTablet'     => '',
		'boxBottomPaddingTablet'   => '',
		'boxTopPaddingMobile'      => '',
		'boxRightPaddingMobile'    => '',
		'boxLeftPaddingMobile'     => '',
		'boxBottomPaddingMobile'   => '',
		'boxPaddingUnit'           => 'px',
		'boxPaddingUnitTablet'     => 'px',
		'boxPaddingUnitMobile'     => 'px',
	)
);
