<?php
/**
 * Attributes File.
 *
 * @since 2.1.0
 *
 * @package uagb
 */

$box_border_attribute = UAGB_Block_Helper::uag_generate_border_attribute( 'box' );

return array_merge(
	array(
		'endDateTime'                 => '2023-01-01T00:00:00Z',
		'showSeparator'               => true,
		'separatorType'               => 'colon',
		'showLabels'                  => true,
		'labelDays'                   => __( 'DAYS', 'ultimate-addons-for-gutenberg' ),
		'labelHours'                  => __( 'HOURS', 'ultimate-addons-for-gutenberg' ),
		'labelMinutes'                => __( 'MINUTES', 'ultimate-addons-for-gutenberg' ),
		'labelSeconds'                => __( 'SECONDS', 'ultimate-addons-for-gutenberg' ),
		// Digit.
		'digitLoadGoogleFonts'        => false,
		'digitColor'                  => '',
		'digitFontFamily'             => 'Default',
		'digitFontWeight'             => '',
		'digitFontStyle'              => 'normal',
		'digitTransform'              => '',
		'digitDecoration'             => '',
		'digitFontSizeType'           => 'px',
		'digitLineHeightType'         => 'em',
		'digitFontSize'               => '',
		'digitFontSizeTablet'         => '',
		'digitFontSizeMobile'         => '',
		'digitLineHeight'             => '',
		'digitLineHeightTablet'       => '',
		'digitLineHeightMobile'       => '',
		'digitTopMargin'              => '',
		'digitRightMargin'            => '',
		'digitBottomMargin'           => '',
		'digitLeftMargin'             => '',
		'digitTopMarginTablet'        => '',
		'digitRightMarginTablet'      => '',
		'digitBottomMarginTablet'     => '',
		'digitLeftMarginTablet'       => '',
		'digitTopMarginMobile'        => '',
		'digitRightMarginMobile'      => '',
		'digitBottomMarginMobile'     => '',
		'digitLeftMarginMobile'       => '',
		'digitMarginUnit'             => 'px',
		'digitMarginUnitTablet'       => 'px',
		'digitMarginUnitMobile'       => 'px',
		// Label.
		'labelLoadGoogleFonts'        => false,
		'labelColor'                  => '',
		'labelFontFamily'             => 'Default',
		'labelFontWeight'             => '',
		'labelFontStyle'              => 'normal',
		'labelTransform'              => '',
		'labelDecoration'             => '',
		'labelFontSizeType'           => 'px',
		'labelLineHeightType'         => 'em',
		'labelFontSize'               => '',
		'labelFontSizeTablet'         => '',
		'labelFontSizeMobile'         => '',
		'labelLineHeight'             => '',
		'labelLineHeightTablet'       => '',
		'labelLineHeightMobile'       => '',
		'labelTopMargin'              => '',
		'labelRightMargin'            => '',
		'labelBottomMargin'           => '',
		'labelLeftMargin'             => '',
		'labelTopMarginTablet'        => '',
		'labelRightMarginTablet'      => '',
		'labelBottomMarginTablet'     => '',
		'labelLeftMarginTablet'       => '',
		'labelTopMarginMobile'        => '',
		'labelRightMarginMobile'      => '',
		'labelBottomMarginMobile'     => '',
		'labelLeftMarginMobile'       => '',
		'labelMarginUnit'             => 'px',
		'labelMarginUnitTablet'       => 'px',
		'labelMarginUnitMobile'       => 'px',
		// Separator Styles.
		'separatorFontFamily'         => '',
		'separatorFontWeight'         => '',
		'separatorFontStyle'          => '',
		'separatorFontSize'           => '',
		'separatorColor'              => '',
		'separatorTransform'          => '',
		'separatorDecoration'         => '',
		'separatorFontSizeType'       => 'px',
		'separatorFontSizeMobile'     => '',
		'separatorFontSizeTablet'     => '',
		'separatorLineHeight'         => '',
		'separatorLineHeightType'     => 'px',
		'separatorLineHeightMobile'   => '',
		'separatorLineHeightTablet'   => '',
		'separatorRightSpacing'       => '',
		'separatorRightSpacingTablet' => '',
		'separatorRightSpacingMobile' => '',
		'separatorTopSpacing'         => '',
		'separatorTopSpacingTablet'   => '',
		'separatorTopSpacingMobile'   => '',
		// Block Margin.
		'blockTopMargin'              => '',
		'blockRightMargin'            => '',
		'blockLeftMargin'             => '',
		'blockBottomMargin'           => '',
		'blockTopMarginTablet'        => '',
		'blockRightMarginTablet'      => '',
		'blockLeftMarginTablet'       => '',
		'blockBottomMarginTablet'     => '',
		'blockTopMarginMobile'        => '',
		'blockRightMarginMobile'      => '',
		'blockLeftMarginMobile'       => '',
		'blockBottomMarginMobile'     => '',
		'blockMarginUnit'             => 'px',
		'blockMarginUnitTablet'       => 'px',
		'blockMarginUnitMobile'       => 'px',
		// Block Padding.
		'blockTopPadding'             => '',
		'blockRightPadding'           => '',
		'blockLeftPadding'            => '',
		'blockBottomPadding'          => '',
		'blockTopPaddingTablet'       => '',
		'blockRightPaddingTablet'     => '',
		'blockLeftPaddingTablet'      => '',
		'blockBottomPaddingTablet'    => '',
		'blockTopPaddingMobile'       => '',
		'blockRightPaddingMobile'     => '',
		'blockLeftPaddingMobile'      => '',
		'blockBottomPaddingMobile'    => '',
		'blockPaddingUnit'            => 'px',
		'blockPaddingUnitTablet'      => 'px',
		'blockPaddingUnitMobile'      => 'px',
		// Box Padding.
		'boxTopPadding'               => '',
		'boxRightPadding'             => '',
		'boxLeftPadding'              => '',
		'boxBottomPadding'            => '',
		'boxTopPaddingTablet'         => '',
		'boxRightPaddingTablet'       => '',
		'boxLeftPaddingTablet'        => '',
		'boxBottomPaddingTablet'      => '',
		'boxTopPaddingMobile'         => '',
		'boxRightPaddingMobile'       => '',
		'boxLeftPaddingMobile'        => '',
		'boxBottomPaddingMobile'      => '',
		'boxPaddingUnit'              => 'px',
		'boxPaddingUnitTablet'        => 'px',
		'boxPaddingUnitMobile'        => 'px',
		// Box Align.
		'align'                       => 'center',
		'alignTablet'                 => '',
		'alignMobile'                 => '',
		// Box Align.
		'boxAlign'                    => 'center',
		'boxAlignTablet'              => '',
		'boxAlignMobile'              => '',
		// Box Spacing.
		'boxSpacing'                  => '',
		'boxSpacingTablet'            => '',
		'boxSpacingMobile'            => '',
		// Box Flex.
		'boxFlex'                     => 'column',
		'boxFlexTablet'               => '',
		'boxFlexMobile'               => '',
		// Box Background.
		'boxBgType'                   => 'transparent',
		'boxBgColor'                  => '',
		// Box - Box Shadow.
		// Box Shadow.
		'boxShadowColor'              => '#00000070',
		'boxShadowHOffset'            => 0,
		'boxShadowVOffset'            => 0,
		'boxShadowBlur'               => '',
		'boxShadowSpread'             => '',
		'boxShadowPosition'           => '',
		'boxShadowColorHover'         => '',
		'boxShadowHOffsetHover'       => 0,
		'boxShadowVOffsetHover'       => 0,
		'boxShadowBlurHover'          => '',
		'boxShadowSpreadHover'        => '',
		'boxShadowPositionHover'      => '',
	),
	$box_border_attribute
);
